project:
  type: website

website:
  title: "*Mi Sitio Web*"
  navbar:
    right:
      - icon: github
        menu:
          - text: Mis repositorios
            href: https://github.com/KatherineTajan
format:
  html:
    theme: solar
    css: costum.css  # Referencia al archivo de CSS personalizado

editor: visual
